spring:
  application:
    name: domain-watchdog
  datasource:
    url:      ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    jdbc:
      dialect: postgresql
#  docker:
#    compose:
#      enabled: true
#      file:
#        - docker/docker-compose.db.yml

#jakarta:
#  persistence:
#    jdbc:
#      url:      ${DATASOURCE_URL}
#      user:     ${DATASOURCE_USERNAME}
#      password: ${DATASOURCE_PASSWORD}